application: ehealthideas
version: 5
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: .*
  script: ehealth.py

- url: /favicon.ico
  static_files: /static/images/elogo.icon
  upload: /static/images/elogo.icon
  